#!/usr/bin/env python3
"""This script reads region (VHASS) data file (VHASS_Region_Counts.csv) present into /data_va/ directory, constructs insert queries to insert data into 'usa_va_mrdd_vhass' table.
   It generates 'queries_mrdd_va_vhass.sql' with the insert queries.
   
Created : 07/21/2020

By Shirish P. Dumbre
"""

import csv
import os
from pathlib import Path

def readVHASSData():
    #print(f"readVHASSData() Started")
    
    file_name = Path(f'{(os.environ["BASE_DIR_PATH"])}/data_va_actuals/VHASS_Region_Counts.csv')
    #print(f"#73-file_name = {file_name}")

    schema_name = os.environ["SCHEMA_NAME"]
    data_table = f"{schema_name}.usa_va_mrdd_vhass"
    
    out_file = open(f'queries_mrdd_va_vhass.sql', "w")
    out_file.write(f'-- script generated by gen_mrdd_va_vhass_queries --\n')
    out_file.write("\n-----------------------------------------------\n")
    out_file.write("-- insert regions data from VHASS_Region_Counts.csv data file \n")
    
    with file_name.open() as csv_file:
        next(csv_file) # skip first line - headers
        csv_reader = csv.reader(csv_file, delimiter = ',')

        for row in csv_reader:
        
            #VHASS_Region,Beds,Ventilators
            insert_str = f'INSERT INTO {data_table} (region_id, region_name, total_beds) VALUES '+"\n"

            # Remove any starting and trailing whitespace from each field
            row = [field.strip() for field in row]
            #print(f"Current row = {row}")

            #Name,Region,Confirmed,Deaths,Recovered,Last Update,ID
            #currRegionId, currTotalBeds, currVentilators = row
            
            currRegionId = (row[0])
            
            try:
                currTotalBeds = int(row[1])
            except (ValueError, IndexError):
                currTotalBeds = -1
            
            #print(f"currRegionId = {currRegionId}, currRegionName = {currRegionId}, currTotalBeds = {currTotalBeds}")

            insert_str += f"('{currRegionId}', '{currRegionId}', {currTotalBeds}),\n"

            #print(f"current_insert_str = {insert_str}")
            out_file.write(f"{insert_str[:-2]};"+"\n")
            
    out_file.write(f"UPDATE {data_table} SET total_beds=null WHERE total_beds=-1;")
    #out_file.write(f"SELECT COUNT(*) AS REGION_RECORDS_INSERTED FROM {data_table};")
    out_file.write(f"\\q \n")
    out_file.close()

def main():
    #print(f"main() Started")
    readVHASSData()

if __name__ == '__main__':
   main()

